name : Scripts Test and Push

env:
  IMAGE_NAME: victorianeema/water-quality

on:
  workflow_dispatch:  # This makes it triggerable only manually

jobs:
  push-if-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Get version number for tagging the image
        run: |
          echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: docker/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.VERSION }}